[package]
name = "y2022"
version = "0.0.0"
edition = "2021"

[dependencies]
lib = { path = "../../crates/lib" }

relative-path = "1.7.2"
regex = "*"
pathfinding="4.1"

serde_json ="*"
serde = "*"
serde_derive = "*"

fasthash = "0.4.0"

memoize = "0.3"